### ISSUE TITLE
Terraform test.pypi.org and associated fastly services

### ISSUE THREAD

**Issue by ewdurbin** [python/pypi-infra#95]
Currently the following domains are served from Fastly services which are unmanaged by terraform:

## Warehouse (Staging)
- ~~test-files.pythonhosted.org~~ (Equivalent to "PyPI File Hosting" service)
- ~~test.pythonhosted.org~~ (Equivalent to "PyPI Docs Hosting" service)
- ~~test.pypi.org~~ (Equivalent to "PyPI service")
- ~~test.pypi.io~~ (Equivalent to "PyPI service")
- ~~warehouse-staging.python.org~~ (Equivalent to "PyPI service")

## TestPyPI (Legacy)
- ~~testpypi.python.org~~ (Equivalent to "PyPI service")

Goal is to move all of this to three services that match the production setup (warehouse, files, docs), then abstract any necessary differences to configuration, then build both the test and prod environments from the same Terraform module.

**Comment by ewdurbin** [comment]
Successfully migrated test-files.pythonhosted.org to terraform management with #96

**Comment by cegerhardson** [comment]
Successfully migrated test.pythonhosted.org to terraform with #98

**Comment by cegerhardson** [comment]
Successfully migrated test.pypi.org to terraform with #99

**Comment by ewdurbin** [comment]
Thanks for your work on this @cegerhardson!
